load('data3.mat');
mcmc_cluster();

% p = 2;
% q = 2;
% l = 1;
% numclusters = 2;
% computeLaplacian(X, p, q, l);


function mcmc_cluster()
    num_iterations = 1000;
    burn_in = 50;
    
    load('data3.mat')

    p = 2;
    q = 2;
    l = 1;
    a = 1;
    tau = 2;
    alpha = 1;
    gamma = 1;
    B = 0.9;
    Z = X;
    set_neg = [25 26 27 28];
    set_pos = [280 281 282 283];
    %set_neg = 1:267;
    %set_pos = [];
    
    [L, ~, ~] = computeLaplacian(Z, p, q, l);
    lambda = eig(L);
    [phi, ~] = eig(L);
    
    [num_senators, ~] = size(Z);
    
    label_data = init(num_senators, set_neg, set_pos);
    
    u_0 = zeros(num_senators, 1);
    for i=1:num_senators
        if label_data(i) ~= 0
            u_0(i) = label_data(i);
        else
            u_0(i) = phi(i, 2);
        end
    end
    
    U = zeros(num_senators, num_iterations);
    U(:, 1) = u_0;
    
    u_accept = zeros(1, num_iterations);
    u_accept_avg = zeros(1, num_iterations);

    %%%%%%% Do running average and variance as well %%%%%%
    % f(j, n) represents the average of the sign of the first n clusterings
    f = zeros(num_senators, num_iterations);
    var = zeros(num_senators, num_iterations);
    
    % Initialize f
    % for j=1:num_senators
    %    f(j, 1)=sign(u_0(j));
    % end
    
    for i=1:num_iterations-1
        u_star = (1-B^2)^0.5*U(:,i)+B*compute_rand(lambda, phi, num_senators, a, tau, alpha);

        %%%%% COMPUTE TRANSITION PROBABILITY %%%%%
        transition_p = min(1, likelihood(gamma, label_data, u_star)/likelihood(gamma, label_data, U(:,i)));

        if rand(1) < transition_p %%%% TRANSITION %%%%
            U(:, i+1) = u_star;
            u_accept(i+1) = 1;
        else
            U(:, i+1) = U(:, i);
            u_accept(i+1) = 0;
        end
        
        if i >= burn_in
            f(:, i+1) = ((i-burn_in)*f(:, i) + sign(U(:, i+1)))/(i-burn_in+1);
            var(:, i+1) = 1-f(:, i+1).^2;
            u_accept_avg(i+1) = ((i-burn_in)*u_accept_avg(i) + u_accept(i+1))/(i-burn_in+1);
        end
        
        %%%%%% CODE FOR AVG MOVIE %%%%
        %if mod(i, 100) == 1   
        %    plotBar(f(:, i))
        %    ha = axes('Position',[0 0 1 1],'Xlim',[0 1],'Ylim',[0 1],'Box','off','Visible','off','Units','normalized', 'clipping' , 'off');
        %    str = sprintf('\\bf Step %d', i);
        %    text(0.5, 1, str,'HorizontalAlignment','center','VerticalAlignment', 'top');
        %    fname = sprintf('figs/step_%i.png',i);
        %    print('-r144','-dpng',fname);
        %end
    end
    
    figure(1)
    plot(1:num_iterations, u_accept_avg)
    fname = 'print_runs/acceptance_probability.png';
    print('-r144','-dpng',fname);
    
    plot_me = [(1:10)'; (268:277)'];

    %%%%%%% PRINT RUNNING AVERAGE %%%%%
    plotAvg(f, num_iterations, plot_me, 2)
    fname = 'print_runs/running_avg.png';
    print('-r144','-dpng',fname);
    
    %%%%%%% PRINT RUNNING VARIANCES %%%%%
    %plotVar(var, num_iterations, plot_me)
    
    %%%%% PRINT CLUSTERING %%%%%
    %plotCluster(f, num_iterations, num_senators)
    
    %%%%%%% FINAL VARIANCE %%%%%%%
    %plotBar(var(:, num_iterations))
    
    %%%%%%% FINAL AVG %%%%%%%
    plotBar(f(:, num_iterations), 3)
    fname = 'print_runs/final_avg.png';
    print('-r144','-dpng',fname);
    
    %plotVotes(Z, [371 280], 268:435)
    
    correct_percent = count_votes_correct(f(:, num_iterations), set_neg, set_pos, [zeros(267,1) - 1; zeros(168,1) + 1]);

    run_description = 'MCMC with unnormalized Laplacian prior, fixed alpha and tau, and nonzero gamma.\n';

    print_info_file(run_description, num_iterations, burn_in, p, q, l, B, ...
        gamma, tau, alpha, set_neg, set_pos, correct_percent);
end

function print_info_file(run_description, num_iterations, burn_in, p, q, l, B, ...
    gamma, tau, alpha, set_neg, set_pos, correct_percent)
fileID = fopen('print_runs/run_info.txt','w');
fprintf(fileID, 'This is an autogenerated text file with run info and summary!\n');
fprintf(fileID, ['Description: ' run_description]);
fprintf(fileID, 'Iterations = %d, Burn in period = %d\n', num_iterations, burn_in);
fprintf(fileID, 'Parameters of weight function: p = %d, q = %d, l = %d\n', p, q, l);
fprintf(fileID, 'Beta = %f, Gamma = %d\n', B, gamma);
fprintf(fileID, 'Tau = %f, Alpha = %f\n', tau, alpha);
fprintf(fileID, 'Label Data:\n');
fprintf(fileID, '+1: %d\n', set_pos);
fprintf(fileID, '-1: %d\n', set_neg);
fprintf(fileID, 'Percent of senators correctly classified: %f\n', correct_percent);

end

function u = init(num_senators, set_neg, set_pos)
    u = zeros(num_senators, 1);
    
    % label some of the data
    for i=1:length(set_pos)
        u(set_pos(i))=1;
    end
    for i=1:length(set_neg)
        u(set_neg(i))=-1;
    end
end

function p = count_votes_correct(final_avg, set_neg, set_pos, correct_labels)
p = 0;
remainder = length(correct_labels) - length(set_neg) - length(set_pos);

for i=1:length(correct_labels)
    if ~ismember(i, set_neg) && ~ismember(i, set_pos)
        p = p + 1 - abs(sign(final_avg(i)) - correct_labels(i))/2;
    end
end
p = p / remainder;
end

function l = likelihood(gamma, label_data, u)
    sum = 0;
    for i=1:length(label_data)
        if label_data(i) ~= 0 %%%% TEST IN Z' %%%%
            sum = sum + abs(sign(u(i)) - label_data(i))^2;
        end
    end
    l = exp(-sum/(2*gamma^2));
end

function plotAvg(f, num_iterations, plot_me, k)
    figure(k)
    num_plots = length(plot_me);
    for i = 1:num_plots
        subplot(2, num_plots/2, i);
        plot(1:num_iterations, f(plot_me(i), :))
        title(sprintf('Senator %d', plot_me(i)))
    end
    ha = axes('Position',[0 0 1 1],'Xlim',[0 1],'Ylim',[0 1],'Box','off','Visible','off','Units','normalized', 'clipping' , 'off');
    text(0.5, 1,'\bf Running Averages','HorizontalAlignment','center','VerticalAlignment', 'top');
end

function plotVar(var, num_iterations, plot_me, k)
    figure(k)
    num_plots = length(plot_me);
    for i = 1:num_plots
        subplot(2, 4, i);
        plot(1:num_iterations, var(plot_me(i), :))
        title(sprintf('Senator %d', plot_me(i)))
    end
    ha = axes('Position',[0 0 1 1],'Xlim',[0 1],'Ylim',[0 1],'Box','off','Visible','off','Units','normalized', 'clipping' , 'off');
    text(0.5, 1,'\bf Running Variances','HorizontalAlignment','center','VerticalAlignment', 'top');
    
end

function plotBar(avg, k)
    
    num_pos = 0;
    for i=1:length(avg)
        if avg(i) > 0
            num_pos = num_pos + 1;
        end
    end

    posx = zeros(num_pos,1);
    posy = zeros(num_pos,1);
    ppos = 1;
    negx = zeros(435-num_pos,1);
    negy = zeros(435-num_pos,1);
    pneg = 1;
    for i=1:length(avg)
        if avg(i) > 0
            posx(ppos) = i;
            posy(ppos) = avg(i);
            ppos = ppos + 1;
        else
            negx(pneg) = i;
            negy(pneg) = avg(i);
            pneg = pneg + 1;
        end
    end
    
    
    figure(k)
    clf
    hold on
    bar(posx, posy, 'b')
    bar(negx, negy, 'r')
    hold off
end

function u = compute_rand(lambda, phi, num_senators, a, tau, alpha)
    u = 0;
    for j=2:num_senators
        zeta = normrnd(0, 1);
        u = u + eigvalweight(lambda(j), a, tau, alpha) * zeta * phi(:,j);
    end
end

function w = eigvalweight(lambda, a, tau, alpha)
    w = a*(lambda + tau^2)^(-1/2*alpha);
end

function plotEigenvectors(L)
    [V, ~] = eig(L);
    
    % Plot eigenvectors and determine clustering
    num_plots = 1;
    figure(4)
%     for i = 1:num_plots
%         subplot(2, 2, i);
%         plot(1:length(V(:, i)), V(:, i))
%     end
    plot(1:length(V(:,2)), V(:, 2))

end

function [L, L_sym, L_rw] = computeLaplacian(X, p, q, l)
    %compute Laplacian matrices
    [n, ~] = size(X);
    
    W = zeros(n);
    D = zeros(n);
    for i=1:n
        sum = 0;
        for j=1:n
            x = X(i,:);
            y = X(j,:);
            W(i, j) = weight(x, y, l, p, q);
            sum = sum + W(i, j);
        end
        D(i, i) = sum;
    end
    L = D - W; 
    L_sym = sqrtm(inv(D)) * L * sqrtm(inv(D));
    L_rw = inv(D) * L;
    %plotEigenvectors(L)
end

function d = dist(x, y, p, q)
%Lp of x - y raised to the qth power
    d = norm(x - y, p)^q;
end

function w = weight(x, y, l, p, q)
%weight function with given metric and length-scale parameter
    w = exp(-dist(x, y, p, q)/ 2 / l^2);
end